version: 2
orbs:
  # This Orb includes the following:
  # - checkout current repository
  # - npm install with caching
  # - start the server
  # - wait for the server to respond
  # - run Cypress tests
  # - store videos and screenshots as artifacts on CircleCI
  #https://github.com/cypress-io/circleci-orb/blob/master/docs/examples.md
  cypress: cypress-io/cypress@1.29.0
  node: circleci/node@1.1

executors:
  with-chrome:
    docker:
      - image: 'cypress/browsers:node14.17.6-chrome100-ff98'

workflows:
  version: 2
  test:
    jobs:
      - cypress/run:
          env: 'REACT_APP_NOT_SECRET_CODE=https://express-api-react-notion.vercel.app,CYPRESS_BASE_URL=http://localhost:3000'
          executor: cypress/base-14
          start: npm start
          wait-on: 'http://localhost:3000'
          store_artifacts: true          