version: 2.1
orbs:
  # This Orb includes the following:
  # - checkout current repository
  # - npm install with caching
  # - start the server
  # - wait for the server to respond
  # - run Cypress tests
  # - store videos and screenshots as artifacts on CircleCI
  #https://github.com/cypress-io/circleci-orb/blob/master/docs/examples.md
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/run:
          yarn: true
          cache-key: 'yarn-packages-{{ arch }}-{{ checksum "yarn.lock" }}'
          env: 'REACT_APP_NOT_SECRET_CODE=https://express-api-react-notion.vercel.app,CYPRESS_BASE_URL=http://localhost:3000'
          start: yarn start
<<<<<<< HEAD
          wait-on: 'http://localhost:3000'
=======
          wait-on: 'http://localhost:3000'
              
>>>>>>> e4a83fa29f6a07f970fcc8fb8e74f63696bc6847
